# Generated by Django 4.0.8 on 2023-07-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('raca', models.CharField(blank=True, max_length=254, null=True)),
                ('qntI', models.CharField(blank=True, max_length=254, null=True)),
                ('qntF', models.CharField(blank=True, max_length=254, null=True)),
                ('mortes', models.CharField(blank=True, max_length=254, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
