# Generated by Django 4.0.8 on 2023-07-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixos',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
