# Generated by Django 4.0.8 on 2023-07-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maiorTemperatura', models.CharField(max_length=100, null=True)),
                ('menorTemperatura', models.CharField(blank=True, max_length=254, null=True)),
                ('maiorHumidade', models.CharField(blank=True, max_length=254, null=True)),
                ('menorHumidade', models.CharField(blank=True, max_length=254, null=True)),
                ('racao', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=8, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
