# Generated by Django 4.0.8 on 2023-07-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_diario'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='tipoQnt',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
