# Generated by Django 4.0.8 on 2023-07-07 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_diario_tipoqnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='relacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diario', to='app1.diario')),
                ('fixos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixos', to='app1.fixos')),
            ],
        ),
    ]
