# Generated by Django 4.0.8 on 2023-07-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_relacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacao',
            name='text',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.RemoveField(
            model_name='relacao',
            name='fixos',
        ),
        migrations.AddField(
            model_name='relacao',
            name='fixos',
            field=models.ManyToManyField(to='app1.fixos'),
        ),
    ]
